### ISSUE TITLE
Agregar las comas y los puntos de miles.

### ISSUE THREAD

**Issue by ChrystianDuarte** [pseguel/blackjack#3]
por defecto el tablero muestra 30000, pero mi saldo es de 300.00

**Comment by pseguel** [comment]
Que usuario usaste?

**Comment by ChrystianDuarte** [comment]
chrystianduarte@outlook.com

**Comment by pseguel** [comment]
Según postman tienes 400. Se ve bien formateado. Estamos siguiendo el formato US.

Confírmame para cerrar o seguir revisando

<img width="585" alt="image" src="https://user-images.githubusercontent.com/8932457/66537041-74dc6a00-eaf5-11e9-867c-b1350cf79300.png">

<img width="375" alt="image" src="https://user-images.githubusercontent.com/8932457/66537098-a6edcc00-eaf5-11e9-977c-a9f0c1334f4d.png">

**Comment by ChrystianDuarte** [comment]
Sorry en el bug esta en el podium dashboard http://blackjack-ui.apps.chile-b5a8.open.redhat.com/dashboard.html

**Comment by pseguel** [comment]
Cerrado. 

NOTA: El JSON de la API me lo devuelve sin ceros decimales. De hecho, los agrega al final.
Se corrige via JS.
<img width="458" alt="image" src="https://user-images.githubusercontent.com/8932457/66569281-906d6200-eb41-11e9-887b-0a69cfe1a620.png">
